#Problem 2
#Author- Spondon Kundu
#Project Euler

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
'''

def sum_even_fib(maxseq):
	summ=0
	term1=1
	term2=1
	list_even_fib=[]
	while(summ<=maxseq):
		summ=term1+term2
		term1=term2
		term2=summ
		if(summ%2==0):
			list_even_fib.append(summ)

	return sum(list_even_fib)

if __name__ == '__main__':
	print(sum_even_fib(4000000))

